### ISSUE TITLE
Góp ý

### ISSUE THREAD

**Issue by npqd** [npqd/P4DS_FinalProject#12]
Mong các bạn góp ý để bọn mình hoàn thiện đồ án hơn.

**Comment by dangdohuynhnhu2000** [comment]
Mình thấy đồ án của các bạn rất chỉnh chu và đầu tư. Cách trình bày các bước làm rõ ràng, dễ hiểu và nhiều thông tin. Qua đó, mình cũng học hỏi được nhiều điều từ các bạn.
Chúc các bạn đạt điểm cao nha ^^

Đặng Đỗ Huỳnh Như - 18120219

**Comment by ndtuyen177** [comment]
Mình cũng thấy các bạn đã làm đồ án rất tốt, rất kĩ lưỡng và chi tiết. Từ các khâu chuẩn bị dữ liệu cho đến tiền xử lý, đặt câu hỏi và trả lời đều có ý tưởng hay, trình bày dễ hiểu. 
Mình chỉ có góp ý nhỏ về câu hỏi 3, mối liên quan giữa các trận giao hữu giữa các nước với kết quả World Cup. Trước mỗi kì World Cup thì các đội tuyển đều tranh thủ đá giao hữu với nhau để có thể biết được điểm mạnh, điểm yếu của mình và đối thủ rồi cải thiện. Kết quả của các trận này tuy vô nghĩa nhưng không vô ích, phản ánh được một phần chất lượng và kĩ năng của đội tuyển. Theo mình được biết thì không có đội tuyển nào vượt qua vòng bảng mà thua 2/3 tổng số trận giao hữu, chỉ 1 trường hợp ngoại lệ (Costa Rica năm 2014), đa số thua từ 1/2 là đã bị loại. Và bóng đá mỗi năm là mỗi khác, có thể năm nay đội này rất mạnh, nhưng năm sau bỗng dưng vì lý do nào đó khiến đội này suy yếu rất nhanh. Bạn thử tìm hiểu trận đá giao hữu của các đội trong cùng 1 năm World Cup thử, sẽ có điều rất hay (theo mình biết thì mọi nhà vô địch World Cup từ năm 2002 - 2014 đều không thua bất kì trận giao hữu nào trong năm họ lên ngôi) đây cũng có thể dự đoán được ít ít về nhà vô địch cũng các đội vào tứ kết thay vì 3 năm sẽ khó nhìn ra các đội tuyển.
Chúc các bạn điểm cao! 
Nguyễn Đình Tuyên - 1712888

**Comment by npqd** [comment]
> 
Mình cám ơn nhận xét của bạn nha! Mình sẽ cố gắng sửa và hoàn thiện đồ án hơn. Chúc hai bạn cũng hoàn thành tốt đồ án môn học. Mình cám ơn nhiều
